sudo: required

services:
  - docker

before_install:
  - docker build -t rahuldogra/server -f Dockerfile.dev .

script:
  - docker run rahuldogra/server npm test -- --coverage

after_success:
  #drcypt environment variables
  - openssl enc -aes256 -d -in .enc -out .env -k $SECRET_KEY
  #build production grade dockerfile
  - docker build -t rahuldogra/server .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push rahuldogra/server
