sudo: required

services:
  - docker

before_install:
  - docker build -t rahuldogra/server -f Dockerfile.dev .

script:
  - docker run rahuldogra/server npm test -- --coverage

after_success:
  #build production grade dockerfile
  - docker build -t rahuldogra/server .
  - echo "$DOCKER_PASSWORD" | docker login --username "DOCKER_ID" --password-stdin
  - docker push rahuldogra/server
