version: "3.9"
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /server/node_modules
      - ./:/server
    ports:
      - "3000:3000"
    environment:
      - DB_PROD=${DB_PROD}
    ports:
      - "8080:8080"